### ISSUE TITLE
Primitives checks are lacking constructor checks

### ISSUE THREAD

**Issue by regevbr** [SimonAlling/ts-type-guards#10]
String Number and Boolean can be constructed using the new keyword, rendering the result to be an object and not a primitive (that behave the same as the primitive equivalent). In those cases, typeof will return `object` and not the primitive type.
For example
```js
typeof new String("foo") // object
"foo" instanceof String // false
```
We need to fix those checks

**Comment by SimonAlling** [comment]
Having taken a quick look at the role of `Boolean`, `Number` and `String` in JS and TS, I'm not convinced that the premises in this issue hold – especially the "behave the same as the primitive equivalent" part. Do they really?

First, to avoid any potential confusion, I would like to clarify the distinction between primitive and non-primitive to other readers, using strings as an example. `String` can create either primitive or non-primitive ones, depending on whether it's called without or with the `new` keyword:

```typescript
typeof            "foo" ; // "string" (primitive)
typeof     String("foo"); // "string" (primitive)
typeof new String("foo"); // "object" (non-primitive)
```

One important property non-primitive values _do not_ share with their primitive counterparts is equality semantics:

```typescript
           "foo"  ===            "foo" ; // true
new String("foo") === new String("foo"); // false
```

That's enough for me to be very skeptical of considering a non-primitive string a member of the `string` type, etc.

Here's another example:

```typescript
           "foo"  instanceof String; // false
new String("foo") instanceof String; // true
```

**Could you please elaborate more on the rationale?** Is there for example a real-world use case where you wanted to use `isString` but couldn't because you needed to handle `String` members?

As a side-note, the TypeScript team themselves [issue this recommendation](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-symbol-and-object):

>_Don’t_ ever use the types `Number`, `String`, `Boolean`, `Symbol`, or `Object` These types refer to non-primitive boxed objects that are almost never used appropriately in JavaScript code.
>
>```typescript
>/* WRONG */
>function reverse(s: String): String;
>```
>
>_Do_ use the types `number`, `string`, `boolean`, and `symbol`.
>
>```typescript
>/* OK */
>function reverse(s: string): string;
>```

While that doesn't explicitly say anything about considering members of `String` as members of `string`, it does say something about the non-primitive types in general.

---

One possible solution might be to add explicit guards for this purpose:

```typescript
export function isStringy(x: unknown): x is string | String {
    return typeof x === "string" || x instanceof String;
}
```

Let me know what you think!

**Comment by regevbr** [comment]
@SimonAlling this is indeed one of those weird behaviors of JS.
The equality mismatch is so counter intuitive but at the same time follows the language spec to the letter... 
I think we can add the isStringy method like you suggested (it follows my suggestion in the PR) and we should not mix it up with the isPrimitive function.
I do wonder if we should add the isPrimitiveLike method as well?

**Comment by SimonAlling** [comment]
> I do wonder if we should add the isPrimitiveLike method as well?

This made me laugh. Like, tfw trying to make sense of types in JavaScript. :sweat_smile: 

We should agree on a naming scheme for the new type guards. Suggestions:
* `isBooleany`, `isNumbery`, `isStringy`
* `isBooleanish`, `isNumberish`, `isStringish`
* `isBooleanLike`, `isNumberLike`, `isStringLike`

Also, could you elaborate more on the rationale first? I'd like to get a grasp of why the change is needed before we introduce it. The library has already grown larger than I'd like it to be; I have even thought about shrinking it.

**Comment by regevbr** [comment]
Haha indeed...
The like convention is best in my opinion. 
The rational is that in the off chance some library returns a String, I still need to be able to recognize it in cases, for example, i need to perform regex operation on it.

**Comment by regevbr** [comment]
Thanks @SimonAlling

**Comment by SimonAlling** [comment]
The `is*Like` type guards are in v0.7.0. :slightly_smiling_face:
